// Generated by CoffeeScript 1.4.0
(function() {
  var Controller;

  Controller = (function() {

    function Controller(name) {
      this.name = name;
      this.calc = new Calculator;
      window.onload = init;
    }

    Controller.prototype.init = function() {
      var winButton;
      winButton = document.getElementById("winningButton");
      return winButton.onclick = buttonClicked;
    };

    Controller.prototype.buttonClicked = function() {
      return alert(arg);
    };

    return Controller;

  })();

}).call(this);
