// Generated by CoffeeScript 1.4.0
(function() {
  var Controller;

  Controller = (function() {

    function Controller(name) {
      this.name = name;
      this.calc = new Calculator;
    }

    Controller.prototype.buttonClicked = function(arg) {
      return alert(arg);
    };

    return Controller;

  })();

}).call(this);
